name: flutter_boilerplate
description: A simple boilerplate project
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_secure_storage: ^9.0.0
  form_builder_validators: ^9.1.0
  freezed_annotation: ^2.2.0
  go_router: ^10.1.2
  google_fonts: ^5.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1
  riverpod_annotation: ^2.1.5
  shared_preferences: ^2.0.15


dev_dependencies:

  build_runner: any
  build_verify: any
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  go_router_builder: any
  import_sorter: ^4.6.0
  json_serializable:
  retrofit_generator: ^7.0.8
  riverpod_generator: ^2.3.2
  very_good_analysis: ^5.1.0

## Install derry from https://pub.dev/packages/derry and run derry build, derry watch, derry gen
scripts: derry.yaml

# https://pub.dev/packages/flutter_gen, after new assets run derry gen
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)

  #  integrations:
  #    flutter_svg: true
  #    flare_flutter: true

  assets:
    enabled: true
  fonts:
    enabled: true
  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml
import_sorter:
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/lib\/*
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/lang/en.json
    - assets/
    #- assets/image/
